import { Button } from "@/shared/ui"
import { Typography } from "@mui/material"
import Image from "next/image"
import ImageDescription from "@/images/data_description.png"
import * as Styled from "./ui/DataFormat.styles"
import React from "react"
import {Box} from "@mui/system";
import Link from "next/link";


export const DataFormat = () => {
    return (
        <Styled.AboutDataContainer>
            <Typography
                color="primary"
                variant="h3"
                sx={{ opacity: 0.8, alignSelf: "center" }}
            >
                Data Format
            </Typography>
            <Box sx={{ padding: 2 }}>
                <Typography variant="body1" fontSize={"medium"} fontWeight={"medium"} sx={{ marginBottom: 2, alignSelf: "center" }}>
                    The downloaded archive includes multiple files that provide detailed information about the
                    calculated data:
                </Typography>
                <ul>
                    <li>
                        <Typography variant="body1">
                            <strong>info.txt:</strong> Contains metadata about the performed calculation,
                            including the input parameters.
                        </Typography>
                    </li>
                    <li>
                        <Typography variant="body1">
                            <strong>pt-table.ptbin:</strong> Stores absorption data in a binary format.
                            For information on parsing this file or understanding its structure, refer to the documentation:{" "}
                            <Link
                                href="https://github.com/Razumovskyy/MARFA?tab=readme-ov-file#pt-file-structure"
                                target="_blank"
                                rel="noopener noreferrer"
                            >
                                PT File Structure
                            </Link>
                            .
                        </Typography>
                    </li>
                    <li>
                        <Typography variant="body1">
                            <strong>output.dat:</strong> Provides the same absorption data but in a human-readable format.
                            Note that due to the high resolution of the data, this file can require substantial
                            disk space.
                        </Typography>
                    </li>
                    <li>
                        <Typography variant="body1">
                            <strong>stderr.log:</strong> Captures any standard error output generated by the
                            MARFA core executable.
                        </Typography>
                    </li>
                    <li>
                        <Typography variant="body1">
                            <strong>stdout.log:</strong> Records standard output generated by the
                            MARFA core executable.
                        </Typography>
                    </li>
                </ul>
            </Box>
        </Styled.AboutDataContainer>
    );
};
