# Generated by Django 4.2.16 on 2024-11-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Spectre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        choices=[("CO2", "Co2"), ("H2O", "H2O")], max_length=8
                    ),
                ),
                ("v_start", models.IntegerField()),
                ("v_end", models.IntegerField()),
                ("database_slug", models.CharField(max_length=32)),
                ("line_cut_off", models.CharField(max_length=32)),
                (
                    "chi_factor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tonkov", "Tonkov"),
                            ("pollack", "Pollack"),
                            ("perrin", "Perrin"),
                        ],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "target_value",
                    models.CharField(
                        choices=[("VAC", "Vac"), ("ACS", "Acs")], max_length=3
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="./uploads"),
                ),
                ("file_name", models.TextField(blank=True, max_length=16, null=True)),
                (
                    "spectre_type",
                    models.CharField(
                        choices=[("default", "Default"), ("custom", "Custom")],
                        max_length=8,
                    ),
                ),
                ("zip_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
