# Generated by Django 4.2.17 on 2024-12-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spectres", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spectre",
            name="chi_factor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tonkov", "Tonkov"),
                    ("pollack", "Pollack"),
                    ("perrin", "Perrin"),
                    ("none", "None"),
                ],
                max_length=8,
                null=True,
            ),
        ),
    ]
