# Generated by Django 4.2.17 on 2025-01-02 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spectres", "0002_alter_spectre_chi_factor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spectre",
            name="chi_factor",
        ),
        migrations.RemoveField(
            model_name="spectre",
            name="file",
        ),
        migrations.RemoveField(
            model_name="spectre",
            name="spectre_type",
        ),
    ]
