# Generated by Django 5.1.4 on 2025-01-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spectres", "0003_remove_spectre_chi_factor_remove_spectre_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spectre",
            name="file_name",
        ),
        migrations.AddField(
            model_name="spectre",
            name="density",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="spectre",
            name="pressure",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="spectre",
            name="temperature",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
