# Generated by Django 5.1.4 on 2025-01-02 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spectres", "0004_remove_spectre_file_name_spectre_density_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spectre",
            name="density",
            field=models.FloatField(
                default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
        migrations.AlterField(
            model_name="spectre",
            name="line_cut_off",
            field=models.IntegerField(
                default=25,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(500),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="spectre",
            name="pressure",
            field=models.FloatField(
                default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
        migrations.AlterField(
            model_name="spectre",
            name="species",
            field=models.CharField(
                choices=[
                    ("H2O", "H2O"),
                    ("CO2", "Co2"),
                    ("O3", "O3"),
                    ("N2O", "N2O"),
                    ("CO", "Co"),
                    ("CH4", "Ch4"),
                    ("O2", "O2"),
                    ("NO", "No"),
                    ("SO2", "So2"),
                    ("NO2", "No2"),
                    ("NH3", "Nh3"),
                    ("HNO3", "Hno3"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="spectre",
            name="temperature",
            field=models.FloatField(
                default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
        migrations.AlterField(
            model_name="spectre",
            name="v_end",
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(14000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="spectre",
            name="v_start",
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(14000),
                ],
            ),
        ),
    ]
