# Generated by Django 5.1.4 on 2025-01-03 23:59

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spectres", "0005_alter_spectre_density_alter_spectre_line_cut_off_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spectre",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Calculation Request",
                "verbose_name_plural": "Calculation Requests",
            },
        ),
        migrations.AddField(
            model_name="spectre",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime(2025, 1, 1, 0, 0)
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="spectre",
            name="line_cut_off",
            field=models.PositiveIntegerField(
                default=25, validators=[django.core.validators.MaxValueValidator(500)]
            ),
        ),
        migrations.AlterField(
            model_name="spectre",
            name="species",
            field=models.CharField(
                choices=[
                    ("H2O", "H₂O"),
                    ("CO2", "CO₂"),
                    ("O3", "O₃"),
                    ("N2O", "N₂O"),
                    ("CO", "CO"),
                    ("CH4", "CH₄"),
                    ("O2", "O₂"),
                    ("NO", "NO"),
                    ("SO2", "SO₂"),
                    ("NO2", "NO₂"),
                    ("NH3", "NH₃"),
                    ("HNO3", "HNO₃"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="spectre",
            name="v_end",
            field=models.PositiveIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(14000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="spectre",
            name="v_start",
            field=models.PositiveIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(14000),
                ],
            ),
        ),
    ]
