# Generated by Django 5.1.4 on 2025-01-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spectres", "0006_alter_spectre_options_spectre_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spectre",
            name="zip_url",
        ),
        migrations.AddField(
            model_name="spectre",
            name="zip_file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
