# Generated by Django 5.1.4 on 2025-01-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spectres", "0007_remove_spectre_zip_url_spectre_zip_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spectre",
            name="zip_file",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
